package com.rudra.savingbuddy.domain.model

data class UserSettings(
    val id: Int = 0,
    val darkMode: Boolean = false,
    val amoledMode: Boolean = false,
    val darkModeScheduled: Boolean = false,
    val darkModeStartHour: Int = 18,
    val darkModeEndHour: Int = 6,
    val currency: String = "BDT",
    val startOfWeek: String = "Saturday",
    val dailyReminderEnabled: Boolean = true,
    val dailyReminderTime: String = "20:00",
    val billReminderEnabled: Boolean = true,
    val budgetAlertEnabled: Boolean = true,
    val budgetAlertPercentage: Int = 80,
    val goalReminderEnabled: Boolean = true,
    val pushNotificationEnabled: Boolean = true,
    val weeklySummaryEnabled: Boolean = true,
    val goalProgressEnabled: Boolean = false,
    val privacyModeEnabled: Boolean = false,
    val biometricLockEnabled: Boolean = false,
    val defaultAccountId: Long? = null,
    val roundUpEnabled: Boolean = false,
    val roundUpGoalId: Long? = null,
    val roundUpMultiplier: Int = 1,
    val roundUpType: String = "NEAREST_10",
    val totalRoundUpSaved: Double = 0.0,
    val lastRoundUpDate: Long = 0L,
    val dailyRoundUpTotal: Double = 0.0
)